cc_binary(
    name = "modbus_client",
    srcs = ["modbus_client.cpp"],
    linkopts = [
        "-lgflags",
        "-lglog",
        "-lmodbus",
    ],
)

cc_binary(
    name = "modbus_server",
    srcs = ["modbus_server.cpp"],
    linkopts = [
        "-lgflags",
        "-lglog",
        "-lmodbus",
    ],
)
